export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESSFUL = "ADD_PRODUCT_SUCCESSFUL";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const DOWNLOAD_PRODUCTS = "DOWNLOAD_PRODUCTS";
export const DOWNLOAD_PRODUCTS_SUCCESSFUL = "DOWNLOAD_PRODUCTS_SUCCESSFUL";
export const DOWNLOAD_PRODUCTS_ERROR = "DOWNLOAD_PRODUCTS_ERROR";

export const GET_PRODUCT_DELETE = "GET_PRODUCT_DELETE";
export const PRODUCT_DELETED_SUCCESSFUL = "PRODUCT_DELETED_SUCCESSFUL";
export const PRODUCT_DELETED_ERROR = "PRODUCT_DELETED_ERROR";

export const GET_PRODUCT_EDIT = "GET_PRODUCT_EDIT";
export const START_PRODUCT_EDITION = "START_PRODUCT_EDITION";
export const PRODUCT_EDITED_SUCCESSFUL = "PRODUCT_EDITED_SUCCESSFUL";
export const PRODUCT_EDITED_ERROR = "PRODUCT_EDITED_ERROR";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";
